CREATE SCHEMA IF NOT EXISTS PRODUCT;
CREATE TABLE PRODUCT.PRODUCT
(
    ID            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TITLE         varchar(255)      not null,
    COUNT         integer default 0 not null,
    PRICE         numeric(38, 2)    not null,
    DESCRIPTION   varchar(255)      not null,
    CATEGORY_ID   BIGINT            not null,
    CREATED_DATE  timestamp(6)      not null,
    MODIFIED_DATE timestamp(6),
    CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (CATEGORY_ID)
        REFERENCES PRODUCT.CATEGORY (ID)
)