INSERT INTO PRODUCT.CATEGORY (CREATED_DATE, MODIFIED_DATE, NAME)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Category 1'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Category 2'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Category 3'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Category 4'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Category 5'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Category 6'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Category 7'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Category 8'),
       (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Category 9');